#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACM| grep ".js$")
if [ "$FILES" = "" ]; then
  exit 0
fi

pass=true
for file in ${FILES}; do
  result=$(jshint ${file} -c '.jshintrc')
  if [ "$result" != "" ]; then
    echo '\n\033[31mJSHint Validation failed\033[0m'
    echo "$result"
    pass=false
  fi
done

if ! $pass; then
  echo '\n\033[31mPlease fix JSHint errors before commit\033[0m'
  exit 1
else
  exit 0
fi
