sudo: required

language: node_js

node_js:
  - 8.8.0

services:
  - docker --privileged

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker ps

script:
  - npm run lint
  - npm run test
