language: node_js
node_js: 11.14.0

services:
  - docker

before_install:
  - docker-compose --version
  - docker-compose up -d
  - docker ps

script:
  - commitlint-travis
  - yarn lint
  - yarn test
